---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: talentbook-deployment
  labels:
    name: talentbook-pod
    dev: CM
  namespace: deploy-tb-ns

spec:
  replicas: 2
  selector:
    matchLabels:
      name: talentbook-pod
      dev: CM
  template:
    metadata:
      name: talentbook-pod
      labels:
        name: talentbook-pod
        dev: CM
    spec:
      containers:
      - name: talentbook-container
        image: cccheeminnn/talentbook:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: talentbook-secret

---
apiVersion: v1
kind: Service
metadata:
  name: talentbook-svc-lb
  namespace: deploy-tb-ns
spec:
  type: LoadBalancer
  selector:
    name: talentbook-pod
    dev: CM
  ports:
  - name: p80
    port: 80
    targetPort: 8080